apiVersion: apps/v1
kind: Deployment
metadata:
  name: webligaac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webligaac
      service: webligaac 
  template:
    metadata:
      labels:
        app: webligaac 
        service: webligaac 
    spec:
      containers:
      - image: ligaac.azurecr.io/webligaac:latest
        name: webligaac 
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webligaac
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: webligaac 
    service: webligaac

